@BASE_URL= http://localhost:8875
@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzc0OTMxOTMxLCJleHAiOjE3NzYyMjc5MzF9.HOxnl4Asci3qB7el4wsuuzOBA7mA4gTPe_Zlg3jB-OA

# Admin Token
@token2= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzc1MDE1Nzc2LCJleHAiOjE3NzYzMTE3NzZ9.oz_Pe3Z9a5s_QEgTSHq78QEw_NP-Z_uPX-4XyOgqERw

##Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "username": "testuser08",
    "email": "testuser08@mail.mail",
    "password": "123456",
    "confirmPassword": "123456"
}

###Login
POST {{BASE_URL}}/auth/Login
Content-Type: application/json

{
    "email": "testadmin@mail.mail",
    "password": "123456"
}

###Get User Info
GET {{BASE_URL}}/user
Authorization: {{token2}}

###User Update
PATCH {{BASE_URL}}/user/edit
Authorization: {{token2}}
Content-Type: application/json

{
    "username": "Test Change User",
    "password": "654321",
    "info": "Test Change Info"
}

###Recipes
GET {{BASE_URL}}/recipes

###Get user recipes
GET {{BASE_URL}}/recipes/user-recipes
Authorization: {{token2}}

###Recipe Post
POST {{BASE_URL}}/recipes
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Test Recipe 7",
    "ingredients": "Test ingredients",
    "instructions": "Test Instructions",
    "image": "",
    "categoryId": 1,
    "baseSpiritId": 1
}

###Recipe Update
PUT {{BASE_URL}}/recipes/6
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Test Editted Recipe3",
    "ingredients": "Test ingredients",
    "instructions": "Test Instructions",
    "image": "",
    "categoryId": 2,
    "baseSpiritId": 1
}

###Delete Recipe
DELETE {{BASE_URL}}/recipes/5
Authorization: {{token}}

###Category Get
GET {{BASE_URL}}/categories


###Spirits Get
GET {{BASE_URL}}/spirits

###Spirits Post
POST {{BASE_URL}}/spirits
Authorization: {{token2}}
Content-Type: application/json

{
    "name": "Vodka2",
    "details": "Russian Cyka Blyat",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/Smirnoff_Red_Label_8213.jpg"
}

###Spirits Edit
PUT {{BASE_URL}}/spirits/24
Authorization: {{token2}}
Content-Type: application/json

{
    "name": "VodkaVodka",
    "details": "Drink from motherland",
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/Smirnoff_Red_Label_8213.jpg"
}

###Spirit Delete
DELETE {{BASE_URL}}/spirits/3
Authorization: {{token2}}

###Category GET
GET {{BASE_URL}}/categories
Authorization: {{token2}}

###Category CREATE
POST {{BASE_URL}}/categories
Authorization: {{token2}}
Content-Type: application/json

{
    "name": "Holiday's vibe",
    "details": "Enjoy your cocktails made with seasonal ingredients"
}

###Category UPDATE
PUT {{BASE_URL}}/categories/3
Authorization: {{token2}}
Content-Type: application/json

{
    "name": "Vibes of holiday",
    "details": "Enjoy your cocktails made with seasonal ingredients"
}

###Category DELETE
DELETE {{BASE_URL}}/categories/3
Authorization: {{token2}}

###Not Found
GET {{BASE_URL}}/fail