@BASE_URL= http://localhost:8875
@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiaWF0IjoxNzc0MzM4NjcxLCJleHAiOjE3NzU2MzQ2NzF9.4cawKsCK1ghc3CSMSkX2QoK8g_RY3DuBejVBV10AKyg

##Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "username": "testuser51",
    "email": "testuser51@mail.mail",
    "password": "123456",
    "confirmPassword": "123456"
}

###Login
POST {{BASE_URL}}/auth/Login
Content-Type: application/json

{
    "email": "testuser5@mail.mail",
    "password": "123456"
}

###Get User Info
GET {{BASE_URL}}/user
Authorization: {{token}}

###Recipes
GET {{BASE_URL}}/recipes/

###Recipe Post
POST {{BASE_URL}}/recipes
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Test Recipe",
    "ingredients": "Test ingredients",
    "instructions": "Test Instructions",
    "image": "",
    "categoryId": 1,
    "baseSpiritId": 1
}

###Spirits
GET {{BASE_URL}}/spirits

###User
GET {{BASE_URL}}/user

###Admin
GET {{BASE_URL}}/admin

###Not Found
GET {{BASE_URL}}/fail