@BASE_URL= http://localhost:8875
@token= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiaWF0IjoxNzc0NDA5NDE1LCJleHAiOjE3NzU3MDU0MTV9.a9cQvoMos2Z9xDhtctlyVoGREwoaYVs6tw6CpMuTjjg

@token2= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc0NDA5OTA3LCJleHAiOjE3NzU3MDU5MDd9.6p1N3hjYPEkLhSuaCIJPx4ttGoaMvaYd06C-5-ONoRk

##Register
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
    "username": "testuser51",
    "email": "testuser51@mail.mail",
    "password": "123456",
    "confirmPassword": "123456"
}

###Login
POST {{BASE_URL}}/auth/Login
Content-Type: application/json

{
    "email": "testuser@mail.mail",
    "password": "123456"
}

###Get User Info
GET {{BASE_URL}}/user
Authorization: {{token2}}

###Recipes
GET {{BASE_URL}}/recipes

###Get user recipes
GET {{BASE_URL}}/recipes/user-recipes
Authorization: {{token2}}

###Recipe Post
POST {{BASE_URL}}/recipes
Authorization: {{token2}}
Content-Type: application/json

{
    "name": "Test Recipe 7",
    "ingredients": "Test ingredients",
    "instructions": "Test Instructions",
    "image": "",
    "categoryId": 1,
    "baseSpiritId": 1
}

###Recipe Update
PUT {{BASE_URL}}/recipes/6
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Test Editted Recipe3",
    "ingredients": "Test ingredients",
    "instructions": "Test Instructions",
    "image": "",
    "categoryId": 1,
    "baseSpiritId": 1
}

###Delete Recipe
DELETE {{BASE_URL}}/recipes/5
Authorization: {{token}}

###Category Get
GET {{BASE_URL}}/categories


###Spirits
GET {{BASE_URL}}/spirits

###User
GET {{BASE_URL}}/user

###Admin
GET {{BASE_URL}}/admin

###Not Found
GET {{BASE_URL}}/fail